-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 17:34:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES'; */

-- -----------------------------------------------------
-- Schema univsoftsystem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema univsoftsystem
-- -----------------------------------------------------
-- CREATE DATABASE univsoftsystem;

-- -----------------------------------------------------
-- Table `univsoftsystem`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS author (
  id INT NOT NULL,
  firstname VARCHAR(45) NULL,
  lastname VARCHAR(45) NULL,
  company VARCHAR(45) NULL,
  position VARCHAR(45) NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `univsoftsystem`.`program`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS program (
  id INT NOT NULL,
  name VARCHAR(45) NULL,
  annotation VARCHAR(45) NULL,
  version VARCHAR(45) NULL,
  author_id INT NULL,
  type_id INT NULL,
  terms_of_use_id INT NULL,
  dist_url VARCHAR(45) NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `univsoftsystem`.`terms_of_use`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS terms_of_use (
  id INT NOT NULL,
  name VARCHAR(45) NULL,
  condition VARCHAR(45) NULL,
  start_date TIMESTAMP(0) NULL,
  period INT NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `univsoftsystem`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS type (
  id INT NOT NULL,
  name VARCHAR(45) NULL,
  description VARCHAR(45) NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `univsoftsystem`.`usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usage (
  id INT NOT NULL,
  user_id INT NULL,
  program_id INT NULL,
  time TIMESTAMP(0) NULL,
  action VARCHAR(45) NULL,
  info VARCHAR(45) NULL,
  PRIMARY KEY (id))
;


-- -----------------------------------------------------
-- Table `univsoftsystem`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL,
  firstname VARCHAR(45) NULL,
  lastname VARCHAR(45) NULL,
  email VARCHAR(45) NULL,
  password VARCHAR(45) NULL,
  info VARCHAR(45) NULL,
  PRIMARY KEY (id))
;


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */
